apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: desaimilan001/kubernetes:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "1024m"
        ports:
        - containerPort: 8080
