apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: "desaimilan001/order.service"
        resources:
          limits:
            memory: "256Mi"
            cpu: "1024m"
        ports:
        - containerPort: 8082
